### ISSUE TITLE
jerky frames when viewing with Safari

### ISSUE THREAD

**Issue by GavinHuttley** [nbedos/termtosvg#110]
Using `termtosvg` 1.0.0 to produce the attached [bug.svg.zip](https://github.com/nbedos/termtosvg/files/3947612/bug.svg.zip) file.

This recording works fine with Chrome and Firefox but is very jerky on Safari (version 13 macOS Catalina).

**Comment by nbedos** [comment]
This is gonna be hard to debug because I don't have access to a machine running Safari. If you can spare the time, could you please record your screen for a few seconds so that I can see how the animation looks in Safari?

**Comment by GavinHuttley** [comment]
I do not think this is a bug in termtosvg. If I try generating the file using the `-t window_frame_js`, Safari does not play the animation, and does not respond to controls. If I then regenerate the file without the template specified and run it in Safari, it plays fine. But then if I quit Safari, then open it again and try playing the same svg that just worked, you see the behaviour I've recorded below.

[term2svg.mp4.zip](https://github.com/nbedos/termtosvg/files/3953165/term2svg.mp4.zip)

**Comment by nbedos** [comment]
Thanks for following up. Your recording shows frames being translated continuously when they should be translated step by step. This is specified by the CSS property `animation-timing-function` that is defined in the recording:

```css
#screen_view {
    animation-duration: 13572ms;
    animation-iteration-count:infinite;
    animation-name:roll;
    animation-timing-function: steps(1,end);
    animation-fill-mode: forwards;
}
```
However this property is supposed to be supported by Safari from version 9 onward so that's probably not the problem:

* https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
* https://www.w3schools.com/CSSref/css3_pr_animation-timing-function.asp

It's very strange, especially since the animation sometimes works.
